application:
  name: "sample"
  ownerEmail: "sample@example.com"
  cloudProviders: ["kubernetes"]
  slackChannel: "community_org_ci"
  pipelines:
    - name: "DeployApplications"
      executable: true
      stages:
        - name: "CreateSA"
          inherit: "serviceAccount"

        - name: "DeployUtil"
          inherit: "application"
          metadata:
            name: "sample-util"
          labels:
            version: "v1"

        - name: "DbMigration"
          inherit: "runJob"
          commands:
            - "bundle exec rake db:migrate"
            - "bundle exec rake db:seed"
            - "bundle exec rake db:seed_fu"

        - name: "DeployApplication"
          inherit: "application"
          labels:
            version: "v1"

        - name: "CreateService"
          inherit: "service"

        - name: "DeployWorkers"
          inherit: "runPipeline"
          pipeline: "DeployWorkers"

    - name: "DeployWorkers"
      stages:
        - name: "DeployShoryuken"
          inherit: "worker"
          type: "shoryuken"
          metadata:
            name: "sample-shoryuken"
          command: "bundle exec shoryuken -r /sample/lib/default_sqs_worker.rb"

        - name: "DeploySidekiq"
          inherit: "worker"
          type: "sidekiq"
          metadata:
            name: "sample-sidekiq"
          command: "bundle exec sidekiq -C config/sidekiq.yml"
